<?php

/**
 * Banners
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Banners extends BaseBanners
{
	private $table_alias = "banners ba";

	public function SelectBanners()
	{
		try
		{
			//Executa a Query
			$query = Doctrine_Query::create()
			->select('ba.*')
			->from($this->table_alias)
			->where("ba.cod_idioma = ?", LANGUAGE)
			->andWhere("ba.cod_publicado = 1")
			->andWhere("ba.dat_inicio_publicacao <= NOW()")
			->andWhere("ba.dat_termino_publicacao >= NOW()")
			->orderBy("ba.cod_id DESC")
			->execute()
			->toArray();

			//Retorna o resultado
			return $query;
		}
		catch (Doctrine_Exception $e)
		{
			echo $e->getMessage();
		}
	}

}