<?php

/**
 * CepUf
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CepUf extends BaseCepUf
{
public function getEstados(){
		   try {
			
			//Prepara a query
			$query = DOCTRINE_QUERY::create()
			   ->from('cepUf');
			  
			   //Executa a query
			   $recordset = $query->execute();		   

			//Retorna os dados conforme o idioma
			return $recordset;   
			
		} catch (Doctrine_Exception $e) {
			
			echo $e->getMessage();
		}		
	}

}