<?php

/**
 * ContatosHoteis
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ContatosHoteis extends BaseContatosHoteis {

    private $table_alias = "contatosHoteis co";

    public function BuscaEndereco() {
        try {
            $con = Doctrine_Manager::getInstance()->connection();
            $sth = $con->execute("SELECT co.*, cc.txt_cidade, cu.txt_uf, cu.cha_sigla, ht.* 
                                   FROM " . $this->table_alias . ", cepCidades cc, websiteIdiomas wi, hoteis ht, cepUf cu
                                   WHERE co.cod_cidade = cc.cod_id AND co.cod_idioma = wi.cod_id AND co.cod_hotel = ht.cod_relacao_idioma AND co.cod_estado =  cu.cod_id group by co.cod_id");

            $resultado = $sth->fetchAll();

            return $resultado[0];
        } catch (Doctrine_Exception $e) {
            echo $e->getMessage();
        }
    }

    public function SelectContatos() {
        try {
            $con = Doctrine_Manager::getInstance()->connection();
            $sth = $con->execute("SELECT co.*, cc.txt_cidade, cu.txt_uf, cu.cha_sigla, ht.*
                                   FROM " . $this->table_alias . ", cepCidades cc, websiteIdiomas wi, hoteis ht, cepUf cu
                                   WHERE co.cod_cidade = cc.cod_id AND co.cod_idioma = wi.cod_id AND co.cod_hotel = ht.cod_relacao_idioma AND co.cod_estado =  cu.cod_id group by co.cod_id");

            $resultado = $sth->fetchAll();

            return $resultado[0];
        } catch (Doctrine_Exception $e) {
            echo $e->getMessage();
        }
    }

}
