<?php

/**
 * EmailsFormularios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EmailsFormularios extends BaseEmailsFormularios {

    private $table_alias = "emailsFormularios ef";

    public function BuscaDados($id) {
        try {
            $query = Doctrine_Query::create()
                    ->select("ef.txt_email")
                    ->from($this->table_alias)
                    ->where("ef.cod_id = ?", $id)
                    ->limit(1)
                    ->execute()
                    ->toArray();

            return $query[0];
        } catch (Doctrine_Exception $e) {
            echo $e->getMessage();
        }
    }
/*
    public function BuscaDados($id) {


        try {

//Busca os dados
            $recordset = $this->getTable('emailsFormularios')->find($id);

//Retorna o registro
            return $recordset;
        } catch (Doctrine_Exception $e) {

            echo $e->getMessage();
        }
    }
*/
}

