<?php

/**
 * FormularioContato
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FormularioContato extends BaseFormularioContato {

    private $table_alias = "formularioContato fc";

    public function incluirFaleConosco($parametros) {
        try {
            
         
            //Recebe os campos da tabela preenchidos
            $campos_tabela = $this->setValues($this, $parametros, INSERT);

            //Percorre os campos da tabela
            foreach ($campos_tabela as $chave => $valor) {
                //Atribui os valores resgatados para a tabela em quest�o
                $this->$chave = $campos_tabela->$chave;
            }

            $this->cod_idioma = LANGUAGE;
            $this->dat_datahora = date("Y-m-d H-i-s");
            $this->num_ip = $_SERVER['REMOTE_ADDR'];
           
            //Salva o registro no banco de dados
            $this->save();
            //Returna true em caso de sucesso
            return true;
        } catch (Doctrine_Exception $e) {
            echo $e->getMessage();
        }
    }

}