<?php

/**
 * Hoteis
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Hoteis extends BaseHoteis {

    private $table_alias = "hoteis ht";

    public function SelectUltimoRelacionamentoIdioma() {
        try {
            $query = Doctrine_Query::create()
                    ->select("*")
                    ->from($this->table_alias)
                    ->orderBy("cod_relacao_idioma DESC")
                    ->limit(1)
                    ->execute()
                    ->toArray();

            return $query[0];
        } catch (Doctrine_Exception $e) {
            echo $e->getMessage();
        }
    }

}