<?php
/**
 * WebsitePages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class WebsitePages extends BaseWebsitePages
{
	
	//Tabela do Banco de dados
	private $table = "websitePages";
	
	public function getPageInfo($request)
	{
		try{
			//Retorna os dados da tabela
			return $this->getTable($this->table)->findByurl_caminho($request);
			
		}catch(Doctrine_Exception $e)
		{
			echo $e->getMessage();
		}
	}

}